[build]
builder = "NIXPACKS"
buildCommand = "pip install -e ."

[deploy]
startCommand = "cd src; uv run server.py --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 